### ISSUE TITLE
Floating point problems?

### ISSUE THREAD

**Issue by florianhartig** [davcam/BASFOR#2]
Hi David, 

when installing under 64 bit systems, we get these floating point warnings. Also reading on https://github.com/davcam/BASFOR/issues/1, I wonder if this is a problem.

Does BASFOR strictly require either 32 or 64 bit? Thanks!

```
* installing to library 'C:/Users/FlorianHartig/Documents/R/win-library/3.4'
* installing *source* package 'BASFOR' ...
** libs
c:/Rtools/mingw_64/bin/gfortran    -O2  -mtune=core2 -c  parameters.f90 -o parameters.o
c:/Rtools/mingw_64/bin/gfortran    -O2  -mtune=core2 -c  environment.f90 -o environment.o
c:/Rtools/mingw_64/bin/gfortran    -O2  -mtune=core2 -c  management.f90 -o management.o
c:/Rtools/mingw_64/bin/gfortran    -O2  -mtune=core2 -c  tree.f90 -o tree.o
c:/Rtools/mingw_64/bin/gfortran    -O2  -mtune=core2 -c  belowgroundres.f90 -o belowgroundres.o
c:/Rtools/mingw_64/bin/gfortran    -O2  -mtune=core2 -c  soil.f90 -o soil.o
c:/Rtools/mingw_64/bin/gfortran    -O2  -mtune=core2 -c  BASFOR.f90 -o BASFOR.o
BASFOR.f90:166.18:

  if (CL < 1.E-100) then
                  1
Warning: Real constant underflows its kind at (1)
c:/Rtools/mingw_64/bin/gfortran    -O2  -mtune=core2 -c  set_params.f90 -o set_params.o
c:/Rtools/mingw_64/bin/gfortran -shared -s -static-libgcc -o BASFOR.dll tmp.def BASFOR.o belowgroundres.o environment.o management.o parameters.o set_params.o soil.o tree.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.0/bin/x64 -lR
installing to C:/Users/FlorianHartig/Documents/R/win-library/3.4/BASFOR/libs/x64
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (BASFOR)
```

**Comment by davcam** [comment]
Hi Florian,

When I compile the package I set the following compiler options in the Makevars file

FC = $(BINPREF)gfortran $(M_ARCH)
FCFLAGS = -O3 -fdefault-real-8 $(DEBUGFLAG) -mtune=core2

This promotes all the reals to double.

The main reason for this is that numbers in R are double precision.

So having reals as double precision in FORTRAN eases the interface with R in for example 

run_model <- function(ft      = FORTYPE,
                      rstrt   = RESTRT,
                      p       = params,
                      w       = matrix_weather,
                      calf    = init$calendar_fert,
                      calN    = init$calendar_Ndep,
                      calpT   = init$calendar_prunT,
                      caltT   = init$calendar_thinT,
                      n       = NDAYS,
                      NOUT    = init$NOUT) {

  output <- .Fortran('BASFOR',ft,rstrt,p,w,calf,calN,calpT,caltT,n,NOUT,
                     matrix(0,n,NOUT)) [[11]]
  return(output)
}

**Comment by florianhartig** [comment]
Hi David, many thanks, that did the trick for me. 

Any reason why these options are not in included in the GitHub version? Is this cross-platform compatible?

**Comment by florianhartig** [comment]
And, would that be a better solution for https://github.com/davcam/BASFOR/issues/1 ? Which, btw., should probably be closed, but maybe with a comment?

**Comment by florianhartig** [comment]
Hi David,

sorry, I take this back, this doesn't work properly when adding in the scr/Makevars - are you adding this to your user Makevar?

**Comment by davcam** [comment]
My Makevars is in the directory $HOME/.R and it seems to pick it up fine on Linux, Windows and I would guess MacOS too. 

I should add an install/compile section in the README.md

**Comment by florianhartig** [comment]
Hi David,

fyi, this is what we do now as well, but we moved the makevars to the package directory.
